baseURL = "http://mateimicu.com/"
languageCode = "en-us"
title = "mateimicu"
theme = "kiss"
Paginate = 5
enableRobotsTXT = true

[params.social]
github = "mateimicu"
email = "contact@mateimicu.com"
linkedin = "matei-marius-micu-0246a211a"
rss = "index.xml"

[params.rss]
includeContent = true
authorName = "Matei-Marius Micu"
authorEmail = "contact@mateimicu.com"

[params.social.config]
platforms = ["github", "email", "linkedin", "rss"]


[params.info]
enableSocial = true
related = true
codeCopy = true

[params.sections_right]
"/slides" = "Slides"

[taxonomies]
tag ="tags"
